---
arista-ai1:
  hostname: 192.168.15.151
  groups:
    - arista_eos

arista-ai2:
  hostname: 192.168.15.152
  groups:
    - arista_eos

arista-ai3:
  hostname: 192.168.15.158
  groups:
    - arista_eos

arista-ai4:
  hostname: 192.168.15.156
  groups:
    - arista_eos
