"""
Atlas LangGraph state definition.

Only the fields needed by the Atlas graph are defined here:

    classify_intent → dispatch_agent → build_final_response

Fields
------
prompt
    The raw user input for this turn.
conversation_history
    List of prior ``{"role": "user"|"assistant", "content": ...}`` dicts,
    used to provide multi-turn context to the orchestrator.
username
    Authenticated username from the session cookie; passed through to the
    orchestrator so it can stamp ServiceNow tickets and enforce RBAC.
session_id
    Opaque string identifying this browser session.  Used as the LangGraph
    ``thread_id`` (checkpointer key) and as the Redis key for pending
    clarification state.
request_id
    Per-request identifier generated by the application entrypoint and carried
    through runtime, graph nodes, and tool-facing logging for observability.
intent
    Set by ``classify_intent``:
      - any routed agent key such as ``"troubleshoot"`` or ``"network_ops"``
      - ``"dismiss"`` — bare acknowledgement or unsupported request
rbac_error
    Non-None when an RBAC check fails; carried through to ``build_final_response``
    so a user-friendly error is returned without calling the LLM.
final_response
    The completed ``{"role": "assistant", "content": ...}`` dict, possibly
    also containing ``path_hops`` for the PathVisualization component.
    Set by a dispatched workflow runner (or ``classify_intent`` for early
    exits) and surfaced to the caller by ``process_message``.
"""
from typing import Any
from typing_extensions import TypedDict


class AtlasState(TypedDict, total=False):
    # ── Inputs (set once at graph entry) ──────────────────────────────────
    prompt: str
    conversation_history: list[dict[str, str]]
    username: str | None
    session_id: str | None
    request_id: str | None
    ui_action: dict[str, Any] | None

    # ── Routing signals (set by classify_intent) ──────────────────────────
    intent: str | None
    rbac_error: str | None

    # ── Output (set by dispatched workflow / classify_intent) ─────────────
    final_response: dict[str, Any] | None
